version: '3.7'

services:
  db:
    image: postgres:11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=health_platform
      - POSTGRES_USER=postgres
      - PGUSER=postgres
    networks: 
      - default
    healthcheck:
      test: ['CMD', 'pg_isready']
      timeout: 5s
      retries: 15
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 80:80
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@diploma.com
      - PGADMIN_DEFAULT_PASSWORD=SecurePassword.123
    networks:
      - default

volumes:
    postgres_data:
